#include <iostream>
#include <exception>

using namespace std;

//class Big_Data
//{
//public:
//	Big_Data(unsigned int size)
//	{
//		_memory_pointer = malloc(size);
//		_size = size;
//	}
//
//	//Destro
//	~Big_Data()
//	{
//		free(_memory_pointer);
//	}	
//
//	unsigned int GetSize()
//	{
//		return _size;
//	}
//
//private:
//	void* _memory_pointer;
//	unsigned int _size;
//};
//
//
int main()
{

	std::cout << "kaikki koodit kommentoitu pois!" << std::endl;
//	unsigned long long memory_Taken = 0;
//	unsigned int mem_size = 1;
//
//	while (true)
//	{
//		try {
//			int* myarray = new int[1000];
//			/*memory_Taken += mem_size;
//			std::cout <<  memory_Taken << "\n";*/
//			
//		}
//		catch(exception& e)
//		{
//			std::cout <<"FAILED "<<e.what()<<  "\n";
// 			return;
//		}
//		
//	}
	return 0;

}